#!/bin/sh

git clone ssh://git@git.lookatme.ru:58022/<%= app_name %>.git <%= app_name %>-git
cd <%= app_name %>-git
cp config/database.yml.production config/database.yml
cp config/lam_auth.yml.production config/lam_auth.yml
ln -s public public/<%= app_name %>

